### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by pooyanjamshidi** [csce585-mlsystems/Sustainable-IPA#1]
### Strengths:
- **Relevant and Timely Focus**: Tackling energy consumption in AI is a crucial topic in today’s AI and machine learning landscape, and expanding the IPA framework to include energy consumption metrics is an impactful idea.
- **Well-Defined Problem**: You’ve done a great job defining the current limitations of the IPA system, and why adding energy consumption as a metric is necessary. This clearly highlights the gap in the current framework.
- **Thoughtful Evaluation Plan**: The use of tools like **etrace2** and **NVIDIA’s PCAT** to measure energy consumption is solid. These tools are widely accepted, and they align well with the experiment's goals.

### Suggestions:
1. **Clarifying the Role of Energy in Decision-Making**:
   - You mention that energy consumption may correlate with cost. However, in AI, high accuracy sometimes comes at a higher energy cost. You might want to expand your evaluation to explore **trade-offs** between energy efficiency and performance metrics (accuracy, latency, etc.). Specifically, it would be useful to see whether the "best" model based on current IPA metrics is still optimal when energy consumption is factored in.
   - Consider a scenario where the model chosen by IPA may not be the most energy-efficient. Can the system dynamically shift to more energy-efficient models based on user-defined criteria (like environmental or cost constraints)?

2. **Experiment Design**:
   - In your experiment, you're measuring energy consumption across configurations in the adaptation space. It would be useful to clearly state **how many configurations** you plan to run and analyze. This gives a clearer scope of the experiment.
   - Ensure to clarify **how many test images** or batches of test images you’ll use to measure energy consumption. Energy consumption varies across time and workload, so having a clear, consistent batch size and test images will make the results more interpretable.
   
3. **Exploration of Energy Impact**:
   - Given that energy consumption is influenced by hardware type, it might be interesting to explore how **different hardware setups** (e.g., CPU vs GPU, or cloud instances with different hardware specifications) affect the energy consumption of the pipeline. This could lead to additional insights on which hardware configurations are more energy-efficient for specific models.
   - You could explore future extensions of this work to **support carbon-awareness**, where IPA could potentially select configurations based on the carbon footprint of energy sources at a given time. This could take your "Sustainable-IPA" idea further, especially in the context of **carbon-aware AI**.

4. **Visualization of Results**:
   - Your proposed visualizations are great for showing how energy consumption impacts model selection. Consider breaking the visualizations down further to show **per-metric trade-offs** (e.g., how energy impacts accuracy, cost, latency individually) in different parts of the adaptation space.
   - It might be valuable to provide a **sensitivity analysis**—how small changes in model selection or hardware impact energy consumption. This can help developers decide whether slight improvements in accuracy are worth significant energy increases.

5. **Expanding the Scope**:
   - While you’re starting with the Video pipeline, it would be great to outline a longer-term plan on how this can be generalized to other **non-vision pipelines** or **workflows that use different types of models** (e.g., NLP pipelines). It might also be worth considering whether energy consumption patterns differ significantly across different model types.
   - You could also explore the potential for **real-time energy tracking** during inference, where energy data is continuously updated and developers can adjust their pipelines dynamically. This real-time feedback could offer additional benefits for sustainable AI deployment.

6. **Challenges and Risks**:
   - Real-time energy measurement is inherently noisy, especially in cloud or shared environments. What strategies will you employ to mitigate this noise and ensure **consistent and reliable energy measurements**?
   - Since you're measuring energy consumption on CPUs (and potentially GPUs later), be aware that **background processes** and system variability may affect your energy readings. Make sure to account for this by conducting multiple trials to get an average energy consumption for each configuration.

### Future Considerations:
- **Collaboration with Cloud Providers**: If this becomes a widely adopted feature in IPA, collaborating with cloud providers (e.g., AWS, Azure) could enable even more accurate energy tracking and optimization based on real-time data from their infrastructure.
- **Carbon Footprint Calculators**: Since you're exploring sustainability, you could take this a step further by integrating carbon footprint calculators into IPA, allowing developers to understand the environmental impact of their models more comprehensively.

### Conclusion:
This is an exciting and highly impactful project that addresses the growing need for energy efficiency in AI. Your approach is well-structured, with thoughtful consideration of relevant tools and methods. I’m looking forward to seeing how energy consumption influences model selection and whether it reveals new trade-offs in the adaptation space. Keep pushing toward incorporating sustainability metrics into broader AI workflows! 

Please make sure you also take a look at the comments I provided for the other [team](https://github.com/csce585-mlsystems/ipa-ext/issues/1) working on the IPA extension.

**Comment by reganwillis** [comment]
Thank you for the feedback. The evaluation experiment has been updated accordingly (see above commit). As we get further along we may expand scope in one of the directions outlined in future work.

Additionally, we have a meeting planned to collaborate with the other team.

I'm leaving this issue open until after the evaluation experiment presentation in case you have any other comments.
